### ISSUE TITLE
Yarn missing in Alpine builds

### ISSUE THREAD

**Issue by SamuelHassine** [nikolaik/docker-python-nodejs#80]
Hello,

It seems yarn is missing in the latest Alpine builds:

nikolaik/python-nodejs:python3.11-nodejs20-alpine

/bin/sh: yarn: not found

Kind regards,
Samuel

**Comment by nikolaik** [comment]
Thanks for reporting, what an oversight! I merged a fix in #83 and some test to prevent this from happening in #82 

The fix will be included with the next rebuild

**Comment by SamuelHassine** [comment]
Thanks a lot @nikolaik for your prompt answer and the great work!

**Comment by SamuelHassine** [comment]
Hello @nikolaik,

Sorry to reply again but I still have `/bin/sh: yarn: not found` in the builds based on `nikolaik/python-nodejs:python3.10-nodejs18-alpine`.

I will check if this is a cache problem but I don't think so.

**Comment by SamuelHassine** [comment]
Hello @nikolaik,

I confirm that for the moment Alpine images are still missing yarn.

Kind regards,
Samuel

**Comment by SamuelHassine** [comment]
Hello @nikolaik,

Any news on this?

Kind regards,
Samuel

**Comment by nikolaik** [comment]
Hey! Did a manual rebuild of all images, so yarn should be back in business now. I verified yarn exists in the following combinations locally:

```console
❯ docker run --platform linux/amd64 --pull always nikolaik/python-nodejs:python3.11-nodejs20-alpine yarn --version
python3.11-nodejs20-alpine: Pulling from nikolaik/python-nodejs
Digest: sha256:934fc27f1aad4f2ef04e6d5adb78103f34ae46711557d049b65151b5415a4937
Status: Image is up to date for nikolaik/python-nodejs:python3.11-nodejs20-alpine
1.22.19

❯ docker run --platform linux/amd64 --pull always nikolaik/python-nodejs:python3.10-nodejs18-alpine yarn --version
python3.10-nodejs18-alpine: Pulling from nikolaik/python-nodejs
Digest: sha256:4ecac4ab03dc22fbbcccee5401da1ff11fa6077c5d0ed033a2e51b9ba23c5bdb
Status: Image is up to date for nikolaik/python-nodejs:python3.10-nodejs18-alpine
1.22.19
```
